# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor

# We're using Visual Studio 2015
image: Visual Studio 2015

branches:
  only:
    - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0MrjEwujECMnIaBkI76fNmCpKy5jr9rZx0rAFOM+41frhVfy2r0ldzzoFC4bvGig

# Install the pre-requisites for the build.
install:
  # Download the installer for dotnet.
  - mkdir .\scripts
  - curl -SL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1 -o .\scripts\dotnet-install.ps1
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\dotnet-install.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -Version 1.0.0-preview2-003121 -NoPath'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

# Perform the build.
build_script:
  - dotnet --info
  - bash build/appveyor.sh

# The tests are run as part of the build.
test: off
