# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor

image: Visual Studio 2019

branches:
  only:
    - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0MrjEwujECMnIaBkI76fNmCpKy5jr9rZx0rAFOM+41frhVfy2r0ldzzoFC4bvGig

install:
  # Make sure we get the bash that comes with git, not WSL bash
  - ps: $env:Path = "C:\Program Files\Git\bin;$env:Path"

# Perform the build.
build_script:
  - bash build/appveyor.sh
  - choco install codecov
  - codecov -f coverage/coverage.xml

# The tests are run as part of the build.
test: off
