7name: Push packages to NuGet

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Build and test
      run: |
        build/ci.sh
        dotnet test -c Release -f net8.0 --filter TestCategory=Slow src/NodaTime.Test
        mkdir nuget
        dotnet pack -c Release -o ./nuget src/NodaTime
        dotnet pack -c Release -o ./nuget src/NodaTime.Test

    - name: Push to NuGet
      run: |
        echo "Pushing to NuGet from GitHub disabled until we've got signing sorted"
        exit 1
        # for file in nuget/*.nupkg; do dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} $file; done
