name: Push packages to NuGet

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-18.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: |
        cd src
        dotnet build -c Release
        dotnet test -c Release -f net6.0
        dotnet test -c Release -f net6.0 --filter TestCategory=Slow NodaTime.Test
        mkdir nuget
        dotnet pack -c Release -o ../nuget

    - name: Push to NuGet
      run: |
        echo "Pushing to NuGet from GitHub disabled until we've got signing sorted"
        exit 1
        # for file in nuget/*.nupkg; do dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} $file; done
